import Head from 'next/head';
import { useEffect, useState } from 'react';
import TaskList from '../components/TaskList';
import axios from 'axios';
import { getTasks } from '../helpers/getTasks';

export default function Home() {
	const [task, setTask] = useState('');
	const [taskList, setTaskList] = useState([]);

	useEffect(() => {
		const getTaskList = async () => {
			setTaskList(await getTasks());
		};
		getTaskList();
	}, []);

	const handleSubmit = async (e) => {
		e.preventDefault();
		if (!task) return;
		try {
			await axios.post('http://localhost:3000/api/todos', { title: task });
			setTask('');
			setTaskList(await getTasks());
		} catch (error) {
			console.log(error);
		}
	};

	const handleDelete = async (id) => {
		try {
			await axios.delete(`http://localhost:3000/api/todos/${id}`);
			setTaskList(await getTasks());
		} catch (error) {
			console.log(error);
		}
	};

	const handleComplete = async (id, done) => {
		try {
			await axios.patch(`http://localhost:3000/api/todos/${id}`, {done});
			setTaskList(await getTasks());
		} catch (error) {
			console.log(error);
		}
	}

	return (
		<div className='bg-slate-200 w-full h-screen flex justify-center items-center'>
			<Head>
				<title>ToDo buddy</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='flex flex-col items-center bg-white drop-shadow-[0_4px_4px_rgba(0,0,0,0.25)] p-8'>
				<h1 className='text-3xl font-bold mb-4'>ToDo List</h1>
				<form onSubmit={handleSubmit}>
					<input
						type='text'
						placeholder='e.g. clean dishes'
						value={task}
						onChange={(e) => setTask(e.target.value)}
						className='bg-slate-100 px-4 py-2 rounded-l-full border-slate-500 border-2'
					/>
					<button
						className='bg-sky-800 text-white font-medium rounded-r-full border-2 border-sky-800 py-2 px-4 mr-2 hover:bg-sky-700'
						onClick={() => {}}
					>
						Submit
					</button>
				</form>
				{taskList.length > 0 && (
					<TaskList taskList={taskList} handleDelete={handleDelete} handleComplete={handleComplete}/>
				)}
			</main>
		</div>
	);
}
